<a href="https://colab.research.google.com/github/tokaalaa/DM_Course/blob/main/sheet6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[1,5],
              [2,6],
              [2,10],
              [2,12],
              [3,17],
              [3,12],
              [4,6],
              [4,5],
              [4,7],
              [5,10]              
])
Y = np.array([10, 40, 50, 60, 70, 50, 30, 20, 40, 70])

In [ ]:
X_ = np.column_stack((np.ones((10,1)),X))
XTX = X_.T @ X_
invXTX = np.linalg.inv(XTX)

In [ ]:
XTY = X_.T @ Y
theta = invXTX @ XTY
theta

array([-7.98757764,  4.28571429,  4.34782609])

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, Y)
print(reg.score(X, Y))
print(reg.coef_)
print(reg.intercept_)
reg.predict(test)

0.7873182717903215
[4.28571429 4.34782609]
-7.987577639751542


array([74.43478261, 17.97515528, 30.83229814])

In [ ]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=0.1)
reg = clf.fit(X, Y)
print(reg.score(X, Y))
print(reg.coef_)
print(reg.intercept_)

0.7873143426850626
[4.25531915 4.34467777]
-7.868057374397225


In [ ]:
test =np.array([[3,16],
                [2,4],
                [5,4]               
])
reg.predict(test)

array([74.41274439, 18.021292  , 30.78724945])