<a href="https://colab.research.google.com/github/tokaalaa/DM_Course/blob/main/Sheet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Imports**

In [ ]:
# Import the dependencies
import re
import numpy
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


# **Q2**

## Load Data

In [ ]:
def read_pgm(filename):
    with open(filename, 'rb') as f:
        buffer = f.read()
    try:
        header, width, height, maxval = re.search(
            b"(^P5\s(?:\s*#.*[\r\n])*"
            b"(\d+)\s(?:\s*#.*[\r\n])*"
            b"(\d+)\s(?:\s*#.*[\r\n])*"
            b"(\d+)\s(?:\s*#.*[\r\n]\s)*)", buffer).groups()
    except AttributeError:
        raise ValueError("Not a raw PGM file: '%s'" % filename)
    
    return numpy.frombuffer(buffer,
                            dtype='u1',
                            count=int(width)*int(height),
                            offset=len(header)
                            ).flatten()
Data_Matrix = [] 
label = []                           
for j in range(40):                            
  for i in range(10):
    image = read_pgm("/content/drive/My Drive/DM_sheet5/orl_dataset/s"+ str(j+1)+ "/" + str(i+1) + ".pgm")
    label.append(j+1)
    Data_Matrix.append(image)
  

In [ ]:
Data_Matrix = np.array(Data_Matrix)
print(Data_Matrix.shape)
label = np.array(label)

(400, 10304)


## Split the Dataset into Training and Test sets

In [ ]:
def split_data(Data_Matrix, label,way = 1):
    if way == 1:
      Train_Data, Test_Data = Data_Matrix[::2], Data_Matrix[1::2]
      Train_Label, Test_Label = label[::2], label[1::2]
    else:
      Train_Data, Test_Data, Train_Label, Test_Label = train_test_split(Data_Matrix, label, 
                                                    train_size=0.7)
    return Train_Data, Test_Data, Train_Label, Test_Label

In [ ]:
Train_Data, Test_Data, Train_Label, Test_Label = split_data(Data_Matrix, label,way = 1)

print(Train_Data.shape)

(200, 10304)


## Algorithm

In [ ]:
pc = 5/200
def Naive_Bayes(Train_Data, NClassSamples = 5):
  m,n = Train_Data.shape
  Nclasses = int(m / NClassSamples)
  Train_Data =Train_Data.reshape(Nclasses, NClassSamples, -1)
  mean = numpy.mean(Train_Data, axis=1)
  Z = Train_Data - mean.reshape(40,1,-1)
  var = np.sum(Z**2, axis=1)/NClassSamples
  return mean,var

def Testing(Test_Data, mean, var):
  yhat = []
  for i in range (0, Test_Data.shape[0]):
    exponent = np.exp(-1 * (Test_Data[i,:]-mean)**2 / (2 * var))
    RBF = (1/((math.pi*2)**0.5)* var**0.5) * exponent
    pred = pc * (np.prod(RBF,axis=1)) 
    yhat.append(np.argmax(pred)+1)
  return yhat



## c

In [ ]:
mean, var = Naive_Bayes(Train_Data)
yhat = Testing(Test_Data, mean, var)
accuracy = np.sum(Test_Label == yhat)/Test_Label.shape[0] * 100
print(accuracy)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  


17.0


## d

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Test_Label, yhat)

array([[3, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## e

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)
pca_Data_Matrix = pca.fit_transform(Data_Matrix)
print(pca_Data_Matrix)
Train_Data2, Test_Data2, Train_Label2, Test_Label2 = split_data(pca_Data_Matrix, label,way = 1)

(400, 40)


In [ ]:
mean, var = Naive_Bayes(Train_Data2)
yhat = Testing(Test_Data2, mean, var)
accuracy = np.sum(Test_Label2 == yhat)/Test_Label.shape[0] * 100
print(accuracy)

68.0


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Test_Label2, yhat)

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 4, 0, ..., 0, 0, 0],
       [0, 0, 4, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 3, 0],
       [0, 0, 0, ..., 0, 0, 4]])

# Q3

In [ ]:
C1 = np.array([[2,6],
               [3,5],
               [4,4],
               [5,3],
               [6,2],
               [6,4],
               [6,6],
               [8,4],
               [9,2],
               [9,3]])
C2 = np.array([[3,3],
               [4,3],
               [4,5],
               [5,5],
               [7,3],
               [7,4],
               [7,5]])
C3 = np.array([[7,2],
               [10,1],
               [10,3],
               [10,5],
               [11,3],
               [11,4],
               [12,2],
               [13,4.5]])

In [ ]:
#a
n = 25
pc1 = C1.shape[0]/n
pc2 = C2.shape[0]/n
pc3 = C3.shape[0]/n
#b
mean1 =np.mean(C1,axis=0)
print(mean1)
mean2 =np.mean(C2,axis=0)
print(mean2)
mean3 =np.mean(C3,axis=0)
print(mean3)
Z1 = C1 - mean1
Z2 = C2 - mean2
Z3 = C3 - mean3
cov1 = Z1.T @ Z1 /Z1.shape[0]
cov2 = Z2.T @ Z2 /Z2.shape[0]
cov3 = Z3.T @ Z3 /Z3.shape[0]
print(cov1)
print(cov2)
print(cov3)

[5.8 3.9]
[5.28571429 4.        ]
[10.5     3.0625]
[[ 5.16 -1.92]
 [-1.92  1.89]]
[[2.48979592 0.28571429]
 [0.28571429 0.85714286]]
[[2.75       0.78125   ]
 [0.78125    1.65234375]]


In [ ]:
#c
p1=[6,5]
p2=[9,4]
p3=[8,5]

f1x = (1/((math.pi*2)**0.5)* np.linalg.det(cov1)**0.5) * np.exp(-1 * (p1-mean1).T @ np.linalg.inv(cov1) @ (p1-mean1)/ 2 )
f2x = (1/((math.pi*2)**0.5)* np.linalg.det(cov2)**0.5) * np.exp(-1 * (p1-mean2).T @ np.linalg.inv(cov2) @ (p1-mean2)/ 2 ) 
f3x = (1/((math.pi*2)**0.5)* np.linalg.det(cov3)**0.5) * np.exp(-1 * (p1-mean3).T @ np.linalg.inv(cov3) @ (p1-mean3)/ 2 )
c = np.argmax([f1x*pc1, f2x*pc2, f3x*pc3])  
print("pred1=",str(c+1))

f1x = (1/((math.pi*2)**0.5)* np.linalg.det(cov1)**0.5) * np.exp(-1 * (p2-mean1).T @ np.linalg.inv(cov1) @ (p2-mean1)/ 2 )
f2x = (1/((math.pi*2)**0.5)* np.linalg.det(cov2)**0.5) * np.exp(-1 * (p2-mean2).T @ np.linalg.inv(cov2) @ (p2-mean2)/ 2 ) 
f3x = (1/((math.pi*2)**0.5)* np.linalg.det(cov3)**0.5) * np.exp(-1 * (p2-mean3).T @ np.linalg.inv(cov3) @ (p2-mean3)/ 2 )
c = np.argmax([f1x*pc1, f2x*pc2, f3x*pc3]) 
print("pred2=",str(c+1))

f1x = (1/((math.pi*2)**0.5)* np.linalg.det(cov1)**0.5) * np.exp(-1 * (p2-mean1).T @ np.linalg.inv(cov1) @ (p2-mean1)/ 2 )
f2x = (1/((math.pi*2)**0.5)* np.linalg.det(cov2)**0.5) * np.exp(-1 * (p2-mean2).T @ np.linalg.inv(cov2) @ (p2-mean2)/ 2 ) 
f3x = (1/((math.pi*2)**0.5)* np.linalg.det(cov3)**0.5) * np.exp(-1 * (p2-mean3).T @ np.linalg.inv(cov3) @ (p2-mean3)/ 2 )
c = np.argmax([f1x*pc1, f2x*pc2, f3x*pc3]) 
print("pred3=",str(c+1))

pred1= 1
pred2= 3
pred3= 3


In [ ]:
#d
var1 = np.sum(Z1**2, axis=0)/Z1.shape[0]
var2 = np.sum(Z2**2, axis=0)/Z2.shape[0]
var3 = np.sum(Z3**2, axis=0)/Z3.shape[0]

RBF1 = (1/((math.pi*2)**0.5)* var1**0.5) * np.exp(-1 * (p1-mean1)**2 / (2 * var1))
pred1 = pc1 * (np.prod(RBF1,axis=0)) 
RBF2 = (1/((math.pi*2)**0.5)* var2**0.5) * np.exp(-1 * (p1-mean2)**2 / (2 * var2))
pred2 = pc2 * (np.prod(RBF2,axis=0)) 
RBF3 = (1/((math.pi*2)**0.5)* var3**0.5) * np.exp(-1 * (p1-mean3)**2 / (2 * var3))
pred3 = pc3 * (np.prod(RBF3,axis=0)) 
c = np.argmax([pred1, pred2, pred3]) 
print("pred1=",str(c+1))

RBF1 = (1/((math.pi*2)**0.5)* var1**0.5) * np.exp(-1 * (p2-mean1)**2 / (2 * var1))
pred1 = pc1 * (np.prod(RBF1,axis=0)) 
RBF2 = (1/((math.pi*2)**0.5)* var2**0.5) * np.exp(-1 * (p2-mean2)**2 / (2 * var2))
pred2 = pc2 * (np.prod(RBF2,axis=0)) 
RBF3 = (1/((math.pi*2)**0.5)* var3**0.5) * np.exp(-1 * (p2-mean3)**2 / (2 * var3))
pred3 = pc3 * (np.prod(RBF3,axis=0)) 
c = np.argmax([pred1, pred2, pred3]) 
print("pred2=",str(c+1))

RBF1 = (1/((math.pi*2)**0.5)* var1**0.5) * np.exp(-1 * (p2-mean1)**2 / (2 * var1))
pred1 = pc1 * (np.prod(RBF1,axis=0)) 
RBF2 = (1/((math.pi*2)**0.5)* var2**0.5) * np.exp(-1 * (p2-mean2)**2 / (2 * var2))
pred2 = pc2 * (np.prod(RBF2,axis=0)) 
RBF3 = (1/((math.pi*2)**0.5)* var3**0.5) * np.exp(-1 * (p2-mean3)**2 / (2 * var3))
pred3 = pc3 * (np.prod(RBF3,axis=0)) 
c = np.argmax([pred1, pred2, pred3]) 
print("pred3=",str(c+1))

pred1= 1
pred2= 1
pred3= 1


# Q5

In [ ]:
#e
from sklearn.ensemble import RandomForestClassifier
n_trees = [10,30,100,300]
criterion = ["gini", "entropy"]
for i in range (len(n_trees)):
  for j in range (len(criterion)):
      clf = RandomForestClassifier(n_estimators=n_trees[i],criterion = criterion[j])
      #Train_Data, Test_Data, Train_Label, Test_Label
      clf.fit(Train_Data, Train_Label)
      yhat = clf.predict(Test_Data)
      accuracy = np.sum(Test_Label == yhat)/Test_Label.shape[0] * 100
      print("for n_trees=",n_trees[i],"and criterion=", criterion[j],"accuracy =" , accuracy)

for n_trees= 10 and criterion= gini accuracy = 74.5
for n_trees= 10 and criterion= entropy accuracy = 82.5
for n_trees= 30 and criterion= gini accuracy = 89.5
for n_trees= 30 and criterion= entropy accuracy = 90.0
for n_trees= 100 and criterion= gini accuracy = 90.5
for n_trees= 100 and criterion= entropy accuracy = 96.5
for n_trees= 300 and criterion= gini accuracy = 91.5
for n_trees= 300 and criterion= entropy accuracy = 97.0


In [ ]:
#f
from sklearn.decomposition import PCA
pca = PCA(n_components=100)
pca_Data_Matrix = pca.fit_transform(Data_Matrix)
print(pca_Data_Matrix.shape)
Train_Data3, Test_Data3, Train_Label3, Test_Label3 = split_data(pca_Data_Matrix, label,way = 1)
for i in range (len(n_trees)):
  for j in range (len(criterion)):
      clf = RandomForestClassifier(n_estimators=n_trees[i],criterion = criterion[j])
      #Train_Data, Test_Data, Train_Label, Test_Label
      clf.fit(Train_Data3, Train_Label3)
      yhat = clf.predict(Test_Data3)
      accuracy = np.sum(Test_Label3 == yhat)/Test_Label3.shape[0] * 100
      print("for n_trees=",n_trees[i],"and criterion=", criterion[j],"accuracy =" , accuracy)

(400, 100)
for n_trees= 10 and criterion= gini accuracy = 63.0
for n_trees= 10 and criterion= entropy accuracy = 56.49999999999999
for n_trees= 30 and criterion= gini accuracy = 80.5
for n_trees= 30 and criterion= entropy accuracy = 80.5
for n_trees= 100 and criterion= gini accuracy = 87.0
for n_trees= 100 and criterion= entropy accuracy = 90.0
for n_trees= 300 and criterion= gini accuracy = 86.0
for n_trees= 300 and criterion= entropy accuracy = 93.5


In [ ]:
classes,class_counts = np.unique(label,return_counts=True)
classes,class_counts
v= 100
Dy = Data_Matrix[Data_Matrix[:,0]<=v,:]
DN = Data_Matrix[Data_Matrix[:,0]>v,:]
print(Dy.shape, DN.shape)

(204, 10304) (196, 10304)
1
2


# **Decision_Tree**

In [ ]:
def Decision_Tree(D,labels,min_samples,purity_threshold):
  n = D.shape[0]
  classes,class_counts = np.unique(label,return_counts=True)
  purity = np.max(class_counts/n)
  if n <= min_samples or purity >= purity_threshold:
    c_ = np.argmax(class_counts/n)+1
    #create leaf node and label it with class c_
    return
  j_,split_point_, score_ = 0,0
  for j in range(D.shape[1]):
    v,score = Evaluate_Numeric_Attribute(D, labels, j)
    if score_ < score:
      j_ = j
      split_point_ = v
      score_ = score
  
  Dy, labely = D[D[:,j_]<=v,:], label[D[:,j_]<=v,:]
  DN, labelN = D[D[:,j_]>v,:], label[D[:,j_]>v,:]
  Decision_Tree(Dy, labely,min_samples,purity_threshold), Decision_Tree(DN, labelN,min_samples,purity_threshold)


In [ ]:
def Evaluate_Numeric_Attribute(D, labels,z):
  sorted_D = D[numpy.argsort(D[:, z])].copy()
  M = []
  N = []
  ni = np.zeros((40))#num of classes = 40
  n = D.shape[0]
  for j in range (n-1):
    ni[labels[j]-1] = ni[labels[j]-1] + 1
    if sorted_D[j,z] != sorted_D[j+1,z]:
      v= (sorted_D[j,z] + sorted_D[j+1,z])/2
      M.append(v)
      Nvi= ni
      N.append(Nvi)
  ni[labels[n-1]-1] = ni[labels[n-1]-1] + 1  
  v_, score_ = 0,0
  for v in M: 
    Dy, labely = D[D[:,z]<=v,:], label[D[:,z]<=v,:]
    DN, labelN = D[D[:,z]>v,:], label[D[:,z]>v,:]
    score = Gain(D,labels,Dy, labely, DN, labelN)
    if score_ < score:
      v_ = v
      score_ = score

return v_,score_



In [ ]:
from sklearn.decomposition import PCA
nc = [50,100,150]
for i in range (len(nc)):
    pca = PCA(n_components=nc[i])
    pca_Data_Matrix = pca.fit_transform(Data_Matrix)
    print(pca_Data_Matrix)
    Train_Data4, Test_Data4, Train_Label4, Test_Label4 = split_data(pca_Data_Matrix, label,way = 1)
    Decision_Tree(Train_Data4,Train_Label4,0,1)